# Generated by Django 3.0.8 on 2020-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_publishedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('last_date', models.DateField(null=True)),
            ],
        ),
    ]
