# Generated by Django 3.0.8 on 2021-01-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.ImageField(default='download.png', upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
