# Generated by Django 3.0.8 on 2021-01-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210101_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.ImageField(default='download.png', null=True, upload_to='images/profile'),
        ),
    ]
