# Generated by Django 3.0.8 on 2021-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_mentor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
